project_id = "xekuhgwajypsblglrctp"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.scrape-product]
    verify_jwt = false
  [functions.send-notification]
    verify_jwt = false
  [functions.sync-signing-key]
    verify_jwt = false
